name: 'etl'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
# profile: 'etl' # Para o Databricks
profile: 'etl' 

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


# Configuração para materializar todos os modelos como tabelas delta por padrão
models:
  etl: # Nome do seu projeto
    # Tudo na pasta 'silver' será salvo no schema 'silver'
    silver:
      +materialized: table
      +schema: silver
      +file_format: delta

    # Tudo na pasta 'gold' será salvo no schema 'gold'
    gold:
      +materialized: table
      +schema: gold
      +file_format: delta